Various changes

diff --git a/opt/thecus/nas_backup b/opt/thecus/nas_backup
--- a/opt/thecus/nas_backup
+++ b/opt/thecus/nas_backup
@@ -8,12 +8,12 @@
 # cyruz - http://ciroprincipe.info
 
 LOCK_FILE=/var/run/nas_backup
+LOG_FILE=/var/log/nas_backup.log
 BK_DISK_ID=/dev/disk/by-id/ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E2UUVFRS
 BK_DISK_PART=/dev/disk/by-id/ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E2UUVFRS-part1
 BK_DISK_PART_FS=ext4
 BK_DISK_PART_MOUNT=/mnt/disk_2
 ST_DISK_PART_MOUNT=/mnt/disk_1
-RSYNC_LOG_FILE=/var/log/nas_backup.log
 LED_MNGR=/opt/thecus/nas_led
 
 # This is a cleanup function executed when catching the SIGTERM signal.
@@ -33,7 +33,7 @@ exitgracefully() {
 		ERROR=$ERROR" - SMART test aborted"
 	fi
 	hdparm -Y $BK_DISK_ID
-	logger "$ERROR"
+	echo "$ERROR" >> "$LOG_FILE"
 	[[ -f /proc/thecus_io ]] && $LED_MNGR copy
 	rm -f $LOCK_FILE
 	exit 1
@@ -42,12 +42,12 @@ exitgracefully() {
 # Required tools check.
 for i in smartctl hdparm
 do
-	type $i >/dev/null 2>&1 || { logger -s "nas_backup :: $i not installed, aborting."; exit 1; }
+	type $i >/dev/null 2>&1 || { echo "nas_backup :: $i not installed, aborting." >> "$LOG_FILE"; exit 1; }
 done
 
 # Check if the script is already running (maybe a sync is already going on).
 if [[ -f $LOCK_FILE ]]; then
-	logger -s "nas_backup :: script already running, exiting."
+	echo "nas_backup :: script already running, exiting." >> "$LOG_FILE"
 	exit 1
 fi
 
@@ -63,26 +63,26 @@ echo $$ > $LOCK_FILE
 # Start a SMART test (short everyday and long on saturday).
 # The smartd daemon must be set to notify in case of failure.
 [[ $(date +%a) == "Sat" ]] && TEST=long || TEST=short
-logger -s "nas_backup :: start $TEST SMART test on the backup drive..."
+echo "nas_backup :: start $TEST SMART test on the backup drive..." >> "$LOG_FILE"
 smartctl -t $TEST $BK_DISK_ID
 sleep 1s
 
-logger -s "nas_backup :: waiting for the SMART test to terminate..."
+echo "nas_backup :: waiting for the SMART test to terminate..." >> "$LOG_FILE"
 while [[ $(smartctl -c $BK_DISK_ID | grep "Self-test routine in progress") ]]; do
 	# Sleep in background and wait to trap signals.
 	sleep 5m & wait
 done
 
-logger -s "nas_backup :: mounting backup partition and starting synchronizing..."
+echo "nas_backup :: mounting backup partition and starting synchronizing..." >> "$LOG_FILE"
 mount -t $BK_DISK_PART_FS $BK_DISK_PART $BK_DISK_PART_MOUNT
 cd $ST_DISK_PART_MOUNT
-rsync -XARa --exclude=lost+found --log-file=$RSYNC_LOG_FILE ./* $BK_DISK_PART_MOUNT &
+rsync -XAa --delete --exclude=lost+found --log-file=$LOG_FILE ./ $BK_DISK_PART_MOUNT &
 
 # We started rsync in background so we save its pid and wait to trap signals.
 RSYNC_PID=$!
 wait
 
-logger -s "nas_backup :: unmounting backup partition and putting the drive to sleep..."
+echo "nas_backup :: unmounting backup partition and putting the drive to sleep..." >> "$LOG_FILE"
 umount $BK_DISK_PART
 hdparm -Y $BK_DISK_ID
 
